Grocery_Store/21f2000747/grocery_store/Project/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from . import db as database
from . models import ProductCategories, ProductItem, OrderData, CustomerUser
from flask_login import login_required, current_user,login_user, logout_user, login_required, current_user
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

routes = Blueprint('routes', __name__)

auth = Blueprint("authentication", __name__)


@routes.route('/')
def index():
    return render_template('index.html')

@routes.route('/shop', methods=['GET', 'POST'])
@login_required
def shop():
    if request.method == 'POST':
        item = ProductItem.query.all()
        ordered_quantity = float(request.form.get('ordered_quantity'))
        item_title = request.form.get('item_title')
        product_price = request.form.get('product_cost')
        total = float(product_price)*float(ordered_quantity)
        product_id = request.form.get('product_id')
        status_user = 'NC'
        user_id = current_user.user_id
        item = ProductItem.query.filter_by(product_id=product_id).first()
        item.product_quantity -= ordered_quantity
        new_order = OrderData(ordered_quantity=ordered_quantity, order_total=total,
                          order_status=status_user, customer_id=user_id, item_id=product_id, item_title=item_title, item_cost=product_price)
        database.session.add(new_order)
        database.session.commit()
        flash("Added! Continue Shopping to add more!")
        return redirect(url_for('routes.shop'))

    categories_item = ProductCategories.query.all()
    products_item = ProductItem.query.order_by(ProductItem.creation_date.desc()).all()[::-1]
    return render_template('user_shop.html', categories_item=categories_item, products_item=products_item)


@routes.route('/profile')
@login_required
def profile():
    products_item = ProductItem.query.all()
    orders_item = OrderData.query.all()
    count = 0
    for order in orders_item:
        if order.order_status == 'Purchased' and order.customer_id == current_user.user_id:
            count += 1
    return render_template('user_profile.html', user_name=current_user.user_name, orders_item=orders_item, products_item=products_item, user_id=current_user.user_id, user_username=current_user.user_handle, count=count)

@ routes.route('/search_result', methods=['GET', 'POST'])
@ login_required
def search_result():
    if request.method == 'POST':
        prod = ProductItem.query.all()
        ord = OrderData.query.all()
        quant = float(request.form.get('quant'))
        prod_name = request.form.get('prod_name')
        prod_price = request.form.get('cost')
        total = float(prod_price)*float(quant)
        prod_id = request.form.get('id')
        order_status = 'NC'
        user_id = current_user.user_id
        prod = ProductItem.query.filter_by(product_id=prod_id).first()
        prod.product_quantity -= quant
        new_order = ord(ordered_quantity=quant, order_total=total,
                          order_status=order_status, customer_id=user_id, item_id=prod_id, item_title=prod_name, item_cost=prod_price)
        database.session.add(new_order)
        database.session.commit()
        flash("Added! Continue Shopping to add more!")
        return redirect(url_for('routes.search'))
    
    search_query = request.args.get('query')
    products_item = []
    
    try:
            price = float(search_query)
            products_item = ProductItem.query.filter_by(product_price=price).all()
    except ValueError:
        # Query products by other criteria
        products_item = ProductItem.query.filter(
            (ProductItem.category.has(category_title=search_query)) |
            (ProductItem.product_name.ilike(f'%{search_query}%')) |
            (ProductItem.manufacturing_date == search_query)
        ).all()
    
    categories_item = ProductCategories.query.all()
    
    return render_template('searched_result.html', products_item=products_item, categories_item=categories_item)

@routes.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == 'POST':
        query_search = request.form.get('query_search')
        return redirect(url_for('routes.search_result', query=query_search))

    return render_template('search_item.html')


@routes.route('/cart', methods=['GET', 'POST'])
@login_required
def cart():
    if request.method == 'POST':
        if 'rem' in request.form:
            order_id = int(request.form.get('rem'))
            order = OrderData.query.filter_by(order_id=order_id).first()
            if order:
                product_id = order.item_id
                product = ProductItem.query.filter_by(product_id=product_id).first()
                if product:
                    quantity = order.ordered_quantity
                    product.product_quantity += quantity
                    database.session.delete(order)
                    database.session.commit()
                    return redirect(url_for('routes.cart'))
        elif 'upd' in request.form:
            order_id = int(request.form.get('upd'))
            quantity = float(request.form.get('quant'))
            order = OrderData.query.get(order_id)
            if order:
                old_quantity = order.ordered_quantity
                order.ordered_quantity = quantity
                order.order_total = order.item_cost * order.ordered_quantity
                product = ProductItem.query.get(order.item_id)
                product.product_quantity = product.product_quantity + old_quantity - order.ordered_quantity

                database.session.commit()

                return redirect(url_for('routes.cart'))
        elif 'buyall' in request.form:
            user_id = current_user.user_id
            orders = OrderData.query.filter_by(customer_id=user_id, order_status='NC').all()

            for order in orders:
                product_id = order.item_id
                quantity = order.ordered_quantity
                product = ProductItem.query.filter_by(product_id=product_id).first()
                original_quantity = order.ordered_quantity

                if original_quantity != quantity:
                    product.product_quantity = product.product_quantity + original_quantity - quantity
                    order.ordered_quantity = quantity
                    order.order_total = quantity * order.item_cost

                order.order_status = 'Purchased'

            database.session.commit()

            return redirect(url_for('routes.cart'))

    user_id = current_user.user_id
    orders_data = OrderData.query.filter_by(customer_id=user_id, order_status='NC').all()
    total_price = 0

    for order in orders_data:
        product_id = order.item_id
        quantity = order.ordered_quantity
        product = ProductItem.query.filter_by(product_id=product_id).first()
        subtotal = quantity * order.item_cost
        total_price += subtotal

    products_item = ProductItem.query.all()

    return render_template('user_cart.html', orders_item=orders_data, products_item=products_item, user_id=current_user.user_id, total_cost=total_price)


@routes.route('/admin/manage_product', methods=['GET', 'POST'])
@login_required
def manage_product():
    if request.method == 'POST':
        if 'add_prod' in request.form:
            prod_name = request.form.get('prod_name')
            exp_date = request.form.get('exp_date')
            manu_date = request.form.get('manu_date')
            cat_id = request.form.get('cat_id')
            cost = float(request.form.get('cost'))
            unt = request.form.get('unt')
            quant = float(request.form.get('quant'))
            exp_date = datetime.strptime(exp_date, '%Y-%m-%d').date()
            manu_date = datetime.strptime(
                manu_date, '%Y-%m-%d').date()
            image = request.files['image']
            image_file = image.read()

            
            new_product = ProductItem(
                product_name=prod_name,
                expiration_date=exp_date,
                manufacturing_date=manu_date,
                product_category_id=cat_id,
                product_price=cost,
                product_unit=unt,
                product_quantity=quant,
                image_file=image_file,
                image_url=f'public/{image.filename}'
            )

            database.session.add(new_product)
            database.session.commit()
            flash('Product added successfully.', category='success')
        elif 'remove_product' in request.form:
            prod_id = request.form.get('prod_id')
            prod = ProductItem.query.get(prod_id)
            if prod:
                database.session.delete(prod)
                database.session.commit()
                flash('Product removed successfully.', category='success')
            else:
                flash('Product not found.', category='error')
        elif 'edit_prod' in request.form:
            prod_id = request.form.get('prod_id')
            prod = ProductItem.query.get(prod_id)
            if prod:
                prod.product_name = request.form.get('prod_name')
                exp_date = request.form.get('exp_date')
                manu_date = request.form.get('manu_date')
                exp_date = datetime.strptime(exp_date, '%Y-%m-%d').date()
                manu_date = datetime.strptime(
                    manu_date, '%Y-%m-%d').date()
                prod.expiration_date = exp_date
                prod.manufacturing_date = manu_date
                prod.product_category_id = request.form.get('cat_id')
                prod.product_price = float(request.form.get('cost'))
                prod.product_quantity = float(request.form.get('quant'))
                database.session.commit()
            else:
                flash('Product not found.', category='error')

        if current_user.user_role == 1:

Grocery_Store/21f2000747/grocery_store/Project/templates/admin_login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manager Login</title>
    <link href="/static/_423345b1-a9f0-406e-87d0-67c20d2566d6.jpeg" rel="stylesheet">
    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }
        
        html, body {
            height: 100%;
        }
        
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            background: url(https://images.unsplash.com/photo-1466781783364-36c955e42a7f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2671&q=80);
            background-position: center;
            background-size: cover;
            background-repeat: no-repeat;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        }
        
        .glass {
            background: linear-gradient(135deg, rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0));
            backdrop-filter: blur(20px); 
            -webkit-backdrop-filter: blur(20px);
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
            border: 1px solid rgba(255, 255, 255, 0.18);
        }
        
        .box {
            border-radius: 10px;
            width: 250px;
            height: 350px;
            display: flex;
            align-items: center;
            flex-direction: column;
            justify-content: center;
        }
        
        .user-img {
            height: 100px;
            filter: drop-shadow(0 0 8px rgba(0, 0, 0, 0.2));
            color: #ABC4AA;
        }
        
        .user-name {
            background: #e6e6e6;
            height: 40px;
            display: flex;
            width: 60%;
            align-items: center;
            border-radius: 10px;
            padding: 0 15px;
            margin: 5px 0;
        }
        
        .user-name input{
            background: none;
            border: none;
            outline: none;
            width: 100%;
            height: 100%;
            margin-left: 10px;
        }
        
        .password {
            background: #e6e6e6;
            height: 40px;
            display: flex;
            width: 60%;
            align-items: center;
            border-radius: 10px;
            padding: 0 15px;
            margin: 5px 0;
        }
        
        .password input{
            background: none;
            border: none;
            outline: none;
            width: 100%;
            height: 100%;
            margin-left: 10px;
        }
        
        .user-name,password i {
            color: #686868;
        }
        
        ::placeholder {
            color: #9a9a9a;
        }
        
        .login-btn {
            width: 68%;
            padding: 10px;
            color: white;
            background: green;
            border: none;
            border-radius: 20px;
            cursor: pointer;
            margin-top: 10px;
        }
        
        a {
            font-size: 15px;
            color: #9a9a9a;
            cursor: pointer;
            -webkit-user-select: none; 
            user-select: none; 
            text-decoration: none;
        }
        
        a.forgot {
            margin-top: 15px;
        }
        
        .create {
            display: flex;
            align-items: center;
            position: absolute;
            bottom: 50px;
            
        }
        
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .login {
            background-color: #fff;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
            padding: 20px;
            border-radius: 5px;
            width: 300px;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }


        
        @media (min-width: 768px) {
            .container {
                grid-template-columns: 50% 50%;
                grid-template-areas: "design login";
            }
        
            .design {
                display: block;
            }
        }
    </style>
</head>

<body>
    <form method="POST" action="/admin/login">
        <div class="container">
            <div class="login">
                <h3 class="title">Admin Login</h3>
                <div class="text-input">

                    <input type="text" name="admin_username" placeholder="Username">
                </div>
                <div class="text-input">
                    <input type="password" name="admin_pwd" placeholder="Password">
                </div>
                <button class="login-btn">LOGIN</button>
                <div class="create">
                    <a href="/admin/signup">New Here? Sign UP!</a>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

Grocery_Store/21f2000747/grocery_store/Project/templates/admin_signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User SignUp</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            background: url(https://images.unsplash.com/photo-1466781783364-36c955e42a7f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2671&q=80);
            background-position: center;
            background-size: cover;
            background-repeat: no-repeat;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .login {
            background-color: #fff;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
            padding: 20px;
            border-radius: 5px;
            width: 300px;
        }

        .title {
            text-align: center;
            margin-bottom: 20px;
            color: #333;
        }

        .text-input {
            margin-bottom: 15px;
        }

        .text-input input {
            width: 90%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        .login-btn {
            background-color: #295834;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 3px;
            cursor: pointer;
            width: 100%;
            font-weight: bold;
            transition: background-color 0.3s;
        }

        .login-btn:hover {
            background-color: #2980b9;
        }

        .create {
            margin-top: 15px;
            text-align: center;
            font-size: 14px;
            color: #555;
        }

        .create a {
            color: #3498db;
            text-decoration: none;
        }

        .create a:hover {
            text-decoration: underline;
        }

    </style>
</head>

<body>
    <div class="container">
        <form method="POST">
            <div class="login">
                <h3 class="title">Admin SignUp</h3>
                <div class="text-input">
                    <input type="text" name="name" placeholder="Name">
                </div>
                <div class="text-input">
                    <input type="text" name="username" placeholder="Username">
                </div>
                <div class="text-input">
                    <input type="password" name="pwd" placeholder="Password">
                </div>
                <div class="text-input">
                    <input type="password" name="confpwd" placeholder="Confirm Password">
                </div>
                <button class="login-btn">SignUp</button>
                <div class="create">
                    <a href="login">Already Registered! Click Here</a>
                </div>
            </div>
        </form>
    </div>
</body>

</html>

Grocery_Store/21f2000747/grocery_store/Project/templates/common_adm.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Grocerify</title>
    <style>
        /* Reset default styles */
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            min-height: 100%;
            font-family: sans-serif;
        }

        /* Background and container styles */
        body {
            background-color: #e2e5ed;
        }

        .container {
            max-width: 1024px;
            margin: 0 auto;
            padding: 20px;
        }

        /* Hero section */
        .hero {
            position: relative;
            height: 100vh;
        }

        /* Navbar styles */
        .hero-head {
            padding: 20px;
            background-color: #ffffff; /* White background */
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Subtle shadow */
        }

        .navbar {
            background-color: transparent;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100%;
            z-index: 100;
        }

        .navbar-menu {
            display: flex;
            justify-content: flex-end;
            align-items: center;
        }

        .navbar-item {
            color: #333333; /* Dark gray text */
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            text-decoration: none;
            padding: 10px 15px; /* More padding on top and bottom */
            font-size: 16px;
            transition: transform 0.2s, background-color 0.2s;
        }

        .navbar-item:hover {
            transform: translateY(-2px); /* Slight vertical lift */
            background-color: #f0f0f0; /* Light gray background on hover */
        }

        /* Responsive styles */
        @media (max-width: 768px) {
            .navbar {
                width: 100%;
            }
        }

        @media (max-width: 480px) {
            .navbar {
                width: 90%;
            }
        }

    </style>
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">

                            <a href="{{ url_for('routes.admin') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="/admin/manage_cat" class="navbar-item">
                                Manage Categories
                            </a>
                            <a href="/admin/manage_product" class="navbar-item">
                                Manage Products
                            </a>
                            <a href="{{ url_for('routes.admin_profile') }}" class="navbar-item">
                                Profile
                            </a>
                            <a class="navbar-item" href="/admin/logout">Logout</a>
                            {% else %}
                            <a href="/admin/login" class="navbar-item">
                                Log In
                            </a>
                            <a href="/admin/signup" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

Grocery_Store/21f2000747/grocery_store/Project/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Grocerify</title>
    <link rel="stylesheet" href="\static\modern_styles.css" />
    <style>
        @font-face {
            font-family: 'Abril Fat Face';
            src: url('./public/AbrilFatface-Regular.ttf') format('truetype');
        }

        body {
            background-color: #FFEFDA;
        }

        header{
            display: flex;
            justify-content: space-between;
            margin: 20px;    
            font-family: 'Abril Fat Face';
            font-size: 24px;
            background-color: #FFE3BF;
            height: 60px;
            align-items: center;
            border-radius: 20px;
            box-shadow: 0px 4px 8px rgba(0, 0, .3, .3);
        }

        .logo{
            padding: 10px;
        }

        nav{
            display: flex;
            justify-content: space-between;
            gap: 50px;
            padding: 5px;
        }

        .user-authentic{
            display: flex;
            justify-content: space-between;
            padding: 10px;
        }

        a {
            text-decoration: none;
            color: black;
        }

    </style>
</head>

<body>
    <header>
        <div class="logo">
            <a href="{{ url_for('routes.index') }}" class="navbar-item">
                Grocerify
            </a>
        </div>
        <nav>
            <div class="home-nav"><a href="{{ url_for('routes.index') }}" class="navbar-item">
                    Home
                </a>
            </div>
            <div class="shop-nav">
                {% if current_user.is_authenticated %}
                <a href="/shop" class="navbar-item">
                    Shop
                </a>
                {% endif %}
            </div>
            <div class="login-nav">
                {% if not current_user.is_authenticated %}
                <a href="/login" class="navbar-item">
                    Login
                </a>
                {% endif %}
            </div>
            <div class="signup-nav">
                <a href="/signup" class="navbar-item">
                    Sign Up
                </a>
            </div>
        </nav>
        <div class="user-authentic">
            {% if current_user.is_authenticated %}
            <a href="{{url_for('routes.cart')}}" class="navbar-item">Cart</a>
            <a href="{{url_for('routes.search')}}" class="navbar-item">Search</a>
            <a href="{{ url_for('routes.profile') }}" class="navbar-item">
                Profile
            </a>
            <a class="navbar-item" href="/logout">Logout</a>
            {% endif %}
        </div>
    </header>

    <div class="hero-body">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

Grocery_Store/21f2000747/grocery_store/Project/templates/product_admin.html
{% extends "common_adm.html" %}

{% block content %}
<style>
    body {
        background-color: #F0F5F9;
        font-family: Arial, sans-serif;
    }

    .manage-product {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        margin-bottom: 20px;
        color: #333;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        padding: 5px;
        border-bottom: 1px solid #ddd;
        text-align: left;
    }

    th {
        background-color: #f5f5f5;
    }

    input, select {
        width: 85%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-bottom: 10px;
    }

    button {
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        background-color: #2eaaf2;
        color: #fff;
        font-size: 1em;
        cursor: pointer;
    }

    .edit-button {
        background-color: #68c542;
    }

    .remove-button {
        background-color: #e74c3c;
    }
</style>

<div class="manage-product">
    <h1>Add Product</h1>
    <form method="POST" action="{{ url_for('routes.manage_product') }}" enctype="multipart/form-data">
        <input type="text" name="prod_name" placeholder="Product Name" required>
        <input type="date" name="exp_date" required>
        <input type="date" name="manu_date" required>
        <select name="cat_id" required>
            {% for cat in categories_item %}
            <option value="{{ cat.category_id }}">{{ cat.category_title }}</option>
            {% endfor %}
        </select>
        <input type="number" name="cost" min="0" step="1" placeholder="Price" required>
        <select name="unt" required>
            <option value="piece">Piece</option>
            <option value="kg">Kg</option>
            <option value="litre">Litre</option>
            <option value="dozens">Dozens</option>
            <option value="gallons">Gallons</option>
        </select>
        <input type="number" name="quant" placeholder="Quantity" required>
        <input type="file" name="image" accept="image/*">
        <button onclick="showAlert()" type="submit" name="add_prod">Add Product</button>
    </form>

    <h1>Existing Products</h1>
    {% if products_item %}
    <table>
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Expiry Date</th>
                <th>Manufacture Date</th>
                <th>Category</th>
                <th>Price</th>
                <th>Unit</th>
                <th>Quantity</th>
                <th>Image</th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for prod in products_item %}
            <tr>
                <td>{{ prod.product_name }}</td>
                <td>{{ prod.expiration_date }}</td>
                <td>{{ prod.manufacturing_date }}</td>
                <td>{{ prod.category.category_name }}</td>
                <td>{{ prod.product_price }}</td>
                <td>{{ prod.product_unit }}</td>
                <td>{{ prod.product_quantity }}</td>
                <td>
                    {% if prod.image_url %}
                    <img src="{{ url_for('static', filename=prod.image_url) }}" alt="Product Image" style="max-width: 70px; max-height: 70px;">
                    {% else %}
                    No Image
                    {% endif %}
                </td>
                <td>
                    <form method="POST" action="{{ url_for('routes.manage_product') }}">
                        <input type="hidden" name="prod_id" value="{{ prod.product_id }}">
                        <input type="text" name="prod_name" value="{{ prod.product_name }}" required>
                        <input type="date" name="exp_date" value="{{ prod.expiration_date }}" required>
                        <input type="date" name="manu_date" value="{{ prod.manufacturing_date }}" required>
                        <select name="cat_id" required>
                            {% for cat in categories_item %}
                            <option value="{{ cat.category_id }}" {% if cat.category_id==prod.product_category_id %}selected{% endif %}>
                                {{ cat.category_title }}</option>
                            {% endfor %}
                        </select>
                        <input type="number" name="cost" step="1" value="{{ prod.product_price }}" required>
                        <select name="unit" required>
                            <option value="piece" {% if prod.product_unit=='piece' %}selected{% endif %}>Piece</option>
                            <option value="kg" {% if prod.product_unit=='kg' %}selected{% endif %}>Kg</option>
                            <option value="litre" {% if prod.product_unit=='litre' %}selected{% endif %}>Litre</option>
                            <option value="dozens" {% if prod.product_unit=='dozens' %}selected{% endif %}>Dozens</option>
                            <option value="gallons" {% if prod.product_unit=='gallons' %}selected{% endif %}>Gallons</option>
                        </select>
                        <input type="number" name="quant" value="{{ prod.product_quantity }}" required>
                        <button class="edit-button" onclick="showEdit()" type="submit" value="{{prod.product_id}}" name="edit_prod">Edit</button>
                    </form>
                </td>
                <td>
                    <form method="POST" action="{{ url_for('routes.manage_product') }}">
                        <input type="hidden" name="prod_id" value="{{ prod.product_id }}">
                        <button class="remove-button" onclick="showRemove()" type="submit" name="remove_product">Remove</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No products found.</p>
    {% endif %}
</div>
{% endblock %}